import { useMemo, useState } from "react";
import AdminLayout from "../../components/admin/AdminLayout";
import { AdminPageHeader, AdminResourceState, AdminSearch, AdminTabs } from "../../components/admin/AdminShared";
import useAdminResource, { adminRequest } from "../../hooks/useAdminResource";

const states = [{ value: "todos", label: "Todos" }, { value: "por_revisar", label: "Por revisar" }, { value: "en_progreso", label: "En progreso" }, { value: "correccion", label: "Corrección requerida" }, { value: "aprobado", label: "Aprobado" }];
const labels = { por_revisar: "Por revisar", en_progreso: "En progreso", correccion: "Corrección requerida", aprobado: "Aprobado" };
export default function AdminDS160() {
  const resource = useAdminResource("/admin/ds160");
  const [tab, setTab] = useState("todos"); const [query, setQuery] = useState(""); const [notice, setNotice] = useState("");
  const forms = useMemo(() => resource.data?.formularios || [], [resource.data]);
  const filtered = useMemo(() => forms.filter((item) => (tab === "todos" || item.estado_revision === tab) && `${item.nombre} ${item.correo}`.toLowerCase().includes(query.toLowerCase())), [forms, query, tab]);
  const update = async (item, estado) => { try { await adminRequest(`/admin/ds160/${item.id}`, { method: "PUT", body: JSON.stringify({ estado }) }); setNotice("Formulario actualizado."); resource.retry(); } catch (error) { setNotice(error.message); } };
  return <AdminLayout><AdminPageHeader title="DS-160 Globales" description="Supervisa el progreso y revisión de todos los formularios." />{notice && <p className="admin-feedback" role="status">{notice}</p>}<AdminTabs value={tab} onChange={setTab} items={states} label="Filtrar formularios" /><section className="admin-list-card"><div className="admin-list-toolbar"><AdminSearch value={query} onChange={setQuery} placeholder="Buscar formulario..." /></div><AdminResourceState {...resource} isEmpty={!forms.length} empty="No hay formularios DS-160 registrados." />{!resource.isLoading && !resource.error && forms.length > 0 && <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Solicitante</th><th>Progreso</th><th>Asesor</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{filtered.length ? filtered.map((item) => <tr key={item.id}><td><strong>{item.nombre}</strong><small>{item.perfil || item.correo}</small></td><td><div className="admin-progress"><span><i style={{ width: `${item.progreso}%` }} /></span><b>{item.progreso}%</b></div><small>{item.completado ? "Completado" : `Sección ${item.seccion_actual}`}</small></td><td>{item.asesor || "Sin asignar"}</td><td><span className={`admin-status admin-status--${item.estado_revision === "aprobado" ? "approved" : item.estado_revision === "correccion" ? "correction" : "review"}`}>{labels[item.estado_revision] || item.estado_revision}</span></td><td><select aria-label={`Estado de ${item.nombre}`} value={item.estado_revision} onChange={(event) => update(item, event.target.value)}>{states.slice(1).map((state) => <option key={state.value} value={state.value}>{state.label}</option>)}</select></td></tr>) : <tr><td colSpan="5" className="admin-table-state">No hay formularios que coincidan con los filtros.</td></tr>}</tbody></table></div>}</section></AdminLayout>;
}
