version: '3.8'

services:

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      LOCAL_UPLOAD_DIR: /app/local_uploads
    ports:
      - "3000:3000"
    volumes:
      - local_uploads:/app/local_uploads
    depends_on:
      - db

  frontend:
    build:
       context: ./frontend
       args:
         - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}

    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  local_uploads:
